# Generated by Django 5.0 on 2024-10-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_profile_user_delete_userprofileview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="expense_type",
            field=models.CharField(
                choices=[("Positive", "Positive"), ("Negative", "Negative")],
                max_length=100,
            ),
        ),
    ]
